import type CasesItem from '../types/cases';

export const emojis: CasesItem[] = [
  // animalCase
  { id: 1, emoji: '🐭', rarity: 'common', caseType: 'animal' },
  { id: 2, emoji: '🐰', rarity: 'common', caseType: 'animal' },
  { id: 3, emoji: '🐸', rarity: 'common', caseType: 'animal' },
  { id: 4, emoji: '🐔', rarity: 'common', caseType: 'animal' },
  { id: 5, emoji: '🐷', rarity: 'common', caseType: 'animal' },
  { id: 6, emoji: '🐼', rarity: 'uncommon', caseType: 'animal' },
  { id: 7, emoji: '🦊', rarity: 'uncommon', caseType: 'animal' },
  { id: 8, emoji: '🦝', rarity: 'uncommon', caseType: 'animal' },
  { id: 9, emoji: '🦁', rarity: 'rare', caseType: 'animal' },
  { id: 10, emoji: '🐯', rarity: 'rare', caseType: 'animal' },
  { id: 11, emoji: '🦄', rarity: 'epic', caseType: 'animal' },
  { id: 12, emoji: '🐲', rarity: 'epic', caseType: 'animal' },
  { id: 13, emoji: '🦖', rarity: 'legendary', caseType: 'animal' },
  { id: 14, emoji: '👑', rarity: 'gold', caseType: 'animal' },

  // spaceCase
  { id: 15, emoji: '⭐', rarity: 'common', caseType: 'space' },
  { id: 16, emoji: '🌙', rarity: 'common', caseType: 'space' },
  { id: 17, emoji: '☄️', rarity: 'common', caseType: 'space' },
  { id: 18, emoji: '🛸', rarity: 'common', caseType: 'space' },
  { id: 19, emoji: '🌍', rarity: 'common', caseType: 'space' },
  { id: 20, emoji: '🪐', rarity: 'uncommon', caseType: 'space' },
  { id: 21, emoji: '🌌', rarity: 'uncommon', caseType: 'space' },
  { id: 22, emoji: '🚀', rarity: 'uncommon', caseType: 'space' },
  { id: 23, emoji: '👽', rarity: 'rare', caseType: 'space' },
  { id: 24, emoji: '🌟', rarity: 'rare', caseType: 'space' },
  { id: 25, emoji: '💫', rarity: 'epic', caseType: 'space' },
  { id: 26, emoji: '🌠', rarity: 'epic', caseType: 'space' },
  { id: 27, emoji: '🔭', rarity: 'legendary', caseType: 'space' },
  { id: 28, emoji: '🌞', rarity: 'gold', caseType: 'space' },

  // foodCase
  { id: 29, emoji: '🍎', rarity: 'common', caseType: 'food' },
  { id: 30, emoji: '🍌', rarity: 'common', caseType: 'food' },
  { id: 31, emoji: '🍞', rarity: 'common', caseType: 'food' },
  { id: 32, emoji: '🥕', rarity: 'common', caseType: 'food' },
  { id: 33, emoji: '🥒', rarity: 'common', caseType: 'food' },
  { id: 34, emoji: '🍕', rarity: 'uncommon', caseType: 'food' },
  { id: 35, emoji: '🍔', rarity: 'uncommon', caseType: 'food' },
  { id: 36, emoji: '🌮', rarity: 'uncommon', caseType: 'food' },
  { id: 37, emoji: '🍰', rarity: 'rare', caseType: 'food' },
  { id: 38, emoji: '🍣', rarity: 'rare', caseType: 'food' },
  { id: 39, emoji: '🦞', rarity: 'epic', caseType: 'food' },
  { id: 40, emoji: '🍾', rarity: 'epic', caseType: 'food' },
  { id: 41, emoji: '🎂', rarity: 'legendary', caseType: 'food' },
  { id: 42, emoji: '💎', rarity: 'gold', caseType: 'food' },

  // sportsCase
  { id: 43, emoji: '⚽', rarity: 'common', caseType: 'sports' },
  { id: 44, emoji: '🏀', rarity: 'common', caseType: 'sports' },
  { id: 45, emoji: '🏈', rarity: 'common', caseType: 'sports' },
  { id: 46, emoji: '⚾', rarity: 'common', caseType: 'sports' },
  { id: 47, emoji: '🎾', rarity: 'common', caseType: 'sports' },
  { id: 48, emoji: '🏐', rarity: 'uncommon', caseType: 'sports' },
  { id: 49, emoji: '🏓', rarity: 'uncommon', caseType: 'sports' },
  { id: 50, emoji: '🥊', rarity: 'uncommon', caseType: 'sports' },
  { id: 51, emoji: '🥇', rarity: 'rare', caseType: 'sports' },
  { id: 52, emoji: '🏆', rarity: 'rare', caseType: 'sports' },
  { id: 53, emoji: '🎖️', rarity: 'epic', caseType: 'sports' },
  { id: 54, emoji: '👑', rarity: 'epic', caseType: 'sports' },
  { id: 55, emoji: '🏅', rarity: 'legendary', caseType: 'sports' },
  { id: 56, emoji: '⚡', rarity: 'gold', caseType: 'sports' },
];
